M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu25.04.1} date 2025-11-12T09:27:55-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-12T09:27:55-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu25.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.750
%
G90
G05
T1
X149.51Y-80.105
X155.29Y-80.105
T2
X138.525Y-81.75
X141.275Y-81.75
M30
